import { initLoader, initMobileMenu, initScrollIndicator, initSvgElements, initMouseShadow, initCustomCursor } from "./modules/ui.js";
import { initScrollObserver } from "./modules/observer.js";
import { initModalListeners } from "./modules/projects.js";
import { initCanvas } from "./modules/canvas.js";
import { renderAbout } from "./modules/about.js";
import { renderCredentials } from "./modules/credentials.js";
import { renderInterests } from "./modules/interests.js";
import { renderTimeline } from "./modules/timeline.js";
import { renderVideos } from "./modules/videos.js";
import { renderContact } from "./modules/contact.js";
import { initTypewriter, renderHeroStats } from "./modules/hero.js";

document.addEventListener("DOMContentLoaded", () => {
  initSvgElements();
  initLoader();
  initMobileMenu();
  initScrollIndicator();
  initMouseShadow();
  initCustomCursor();
  initScrollObserver();
  initModalListeners();
  initCanvas();
  initTypewriter();
  renderHeroStats();
  renderAbout();
  renderCredentials();
  renderInterests();
  renderTimeline();
  renderVideos();
  renderContact();
});